# Site Settings
title: Beltram Maldant
url: 'https://beltram.github.io/resume/'
baseurl: '/resume'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
style: styles-6

#Profile information
name: Beltram Maldant
tagline: Architecte / Développeur Rust
age: 32 ans
pic: profile.jpg
summary: "Je suis un développeur Rust travaillant pour Wire. Je suis toujours curieux d'apprendre et soucieux d'écrire du code le plus propre possible. Mon principal domain d'expertise est la cryptographie et plus particulièrement MLS."

#sidebar links
email: beltram.maldant(at)gmail.com
email-displayname: beltram.maldant
phone: xx.xx.xx.xx.xx
linkedin: beltram-maldant-2930b880
linkedin-displayname: Beltram Maldant
github: beltram
twitter: '@BeltramMaldant'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-112698702-1

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
