# Site Settings
title: Beltram Maldant
url: 'https://beltram.github.io/resume/'
baseurl: '/resume'

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Beltram Maldant
tagline: Développeur
age: 26 ans
pic: profile.jpg
summary: "Je suis un développeur nantais passionné par son métier et toutes les stacks techniques dans lesquelles j'évolue.
J'aime par dessus tout apprendre de nouveaux langages et frameworks afin de construire des applis toujours plus performantes et élégantes.
Mon premier souci est d'écrire du code propre, élégant et documenté.<br>
Au cours de mes premières expériences professionnelles j'ai eu la chance de pouvoir toucher à différents langages même si je me considère
actuellement comme un développeur backend Java.<br>
Je suis actuellement à la recherche d'opportunités sur Nantes (ou éventuellement Paris en cas de coup de coeur!) dans des entreprises
innovantes bâtissant des architectures micorservices à l'aide de langages modernes (Kotlin, Rust...)."

#sidebar links
email: beltram.maldant@gmail.com
email-displayname: beltram.maldant
phone: 07.83.53.02.51
linkedin: beltram-maldant-2930b880
linkedin-displayname: Beltram Maldant
github: beltram
twitter: '@BeltramMaldant'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-112698702-1

# Build settings
encoding: "utf-8"
compress_html:
  clippings: all
  ignore:
    envs: development
