# Site Settings
title: Beltram Maldant
url: 'https://beltram.github.io/resume/'
baseurl: '/resume' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6

#Profile information
name: Beltram Maldant
tagline: Developer
pic: profile.jpg
summary: 'Summarise your career here lorem ipsum dolor sit amet, consectetuer adipiscing elit.
You can <a href="#" target="_blank">download this free resume/CV template here</a>. Aenean
commodo ligula eget dolor aenean massa. Cum sociis natoque penatibus et magnis dis parturient
montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu.'

#sidebar links
email: beltram.maldant@gmail.com
phone: 07.83.53.02.51
website: beltram.github.io/resume/ #do not add http://
linkedin: beltram-maldant-2930b880
github: beltram
twitter: '@BeltramMaldant'
#Update all the sections by editing the files inside _data folder.

# Tracker
analytics: UA-83979019-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
